name: rootDir paths test
rootDir: ../../..
prompts:
  - examples/nitro/prompts/reto-1.txt
  - examples/nitro/prompts/reto-2.txt
runners:
  - path: src/chains/summaryBufferMemoryWithTools
    tools:
      loaders:
        - examples/nitro/tools/nitroTools
      enabled:
        - snowboardsSearchTool
        - listSnowboardByFits
        - listSnowboardBySizes
personas:
  - examples/nitro/personas/greg.yml
  - name: Max
    firstMessage: Hi!
    goal: The AI assistant should recommend a model
    profile: |
      You are Greg, a long time rider looking for a backcountry board.
