name: rootDir paths test
rootDir: ../../../gateway
prompts:
  - examples/nitro/prompts/reto-1.txt
  - examples/nitro/prompts/reto-2.txt
runners:
  - path: src/chains/summaryBufferMemoryWithFunctions
    tools:
      loaders:
        - examples/nitro/tools/nitroTools
      enabled:
        - snowboardsSearchTool
        - listSnowboardByFits
        - listSnowboardBySizes
personas:
  - examples/nitro/personas/greg.yml
  - examples/nitro/personas/max.yml
