name: Example Nitro
prompts:
  - examples/nitro/prompts/reto-1.txt
  - examples/nitro/prompts/reto-2.txt
runners:
  - path: src/chains/summaryBufferMemoryWithTools
    tools:
      loaders:
        - examples/nitro/tools/nitroTools
      enabled:
        - snowboardsSearchTool
        - listSnowboardBySizes
  - path: src/chains/summaryBufferMemoryWithTools
    tools:
      loaders:
        - examples/nitro/tools/nitroTools
      enabled:
        - snowboardsByRidingStyle
personas:
  - examples/nitro/personas/greg.yml
  - examples/nitro/personas/max.yml
