create table "private"."lc_cache" (
    "id" bigint generated by default as identity not null,
    "value" jsonb
);


alter table "private"."lc_cache" enable row level security;

CREATE UNIQUE INDEX lc_cache_pkey ON private.lc_cache USING btree (id);

alter table "private"."lc_cache" add constraint "lc_cache_pkey" PRIMARY KEY using index "lc_cache_pkey";


